titles = ['Chef Randall', 'Mrs. Smith', "Andrew's Sister", 
          'John Knox', 'Mr. Yuan', 'Sarah', 'Dan', 
          'Neighbor', 'Jack', 'Program Host', 
          'Jason', 'Game Show Host', 'Michael', 
          'Brandon', 'Gavin', 'Jacob', 'Fisher', 
          'Customer', 'Ron', 'Young Man', 
          'Rental Car Agent', 'Jane', 'Jake', 
          'James', 'Roger', 'Stacy', 'Phil', 'F', 
          'Susan', 'Man', 'Greg', 'Son', 'Sales Associate', 
          'Mr. Adams', 'Tutor', 'Heather', 'Charles', 
          'Merchant', 'Scott', 'Jenny', 'Father', 
          'Mr. Taylor', 'K', 'Maria', 'Micky', 
          'Student', 'Ann', 'Carla', 'Apartment Owner', 
          'Mr. Dong', 'Shawn', 'Ed', 'David', 'B', 'W', 
          'Mechanic', 'Ted', 'Tim', 'Daughter', 'M', 
          'Julie', 'Tenant', 'Server', 'Bill', 
          "Dave's Sister", 'Husband', 'Pancho', 
          'Peter', 'Presenter', 'Sam', 'Dentist', 
          'Terry', 'Jan', 'Daniel', 'Store Employee', 
          'Carl', 'Driver', 'Kids', 'Kelly', 'Teacher', 
          'Mother', 'Mary', 'Security', 'Brenda', 
          'Amanda', 'Ashley', 'Interviewer', 'Mark', 
          'Car Owner', 'News Reporter', 'Ranae', 
          'Stephanie', 'Paul', 'Host', 'Wife', 'Pete', 
          'Car Salesman', 'Nate', 'Hotel Clerk', 
          'Little Girl', 'Beautician', 'Boy', 'Tom', 
          'Josh', 'Employee', 'Ethan', 'Florist', 'Guest', 
          'Lisa', 'Li Ming', 'Joshua', 'Steve', 'Mathew', 
          'Delia Robinson', 'Henry', 'Stuart', 'Mum', 
          'Randall', 'Taxi Driver', 'Rocky', 'Frank', 
          'Alex', 'Travel Agent', 'A', 'Apartment Manager', 
          'Operator', 'Markus', 'Receptionist', 'W1', 
          'Woman', 'Girl', 'Robber', 'Dean', 'Mad', 'Amy', 
          'John', 'Ryan', 'Dave', 'Older Sister', 'Caller', 
          'Andrew', 'Rachel', 'Vet', 'Emily', 'Diane', 
          'Jori', 'Driving Officer', 'Hank', 'Tod', 
          'Telemarketer', 'Sara', 'Patient', 'Passenger', 
          'Nancy', 'Bank Teller', 'Crystal', 
          'Customs Officer', 'Ross', 'Mr. Smith', 
          'The Big Sister', 'R', 'Justin', 'Parent', 
          'Police Officer', 'Doug', 'Berry', 'Dad', 
          'Ronald', 'Waiter', 'Norman', 'Nick', 
          'W2', 'Anna Maria'
          ]

males = ['Ethan', 'Chef Randall', 'Mr. Taylor', 'Bill', 'Berry', 'Andrew', 'Ed', 'Boy', 'Li Ming', 'John Knox', 'Michael', 'Gavin', 'M', 'Mr. Yuan', 'Husband', 'Charles', 'Caller', 'Frank', 'Driving Officer', 'Tod', 'Passenger', 'Micky', 'Tutor', 'K', 'Mad', 'Dan', 'Rental Car Agent', 'Dentist', 'Mr. Dong', 'Heather', 'Presenter', 'Mathew', 'News Reporter', 'Receptionist', 'Henry', 'Robber', 'Man', 'Shawn', 'Car Owner', 'Rocky', 'Patient', 'Mr. Adams', 'Hank', 'Stuart', 'Phil', 'Program Host', 'James', 'Young Man', 'Waiter', 'Brandon', 'Roger', 'Randall', 'Jake', 'Son', 'Taxi Driver', 'Apartment Manager', 'John',  'Host', 'Police Officer','Doug', 'Steve', 'Justin', 'Merchant', 'Jason', 'Tim', 'Jack', 'Crystal', 'Daniel', 'Delia Robinson', 'B', 'Driver', 'Apartment Owner', 'Norman', 'Carl', 'Student', 'Scott', 'Dad', 'Tenant', 'Pete', 'Kids', 'Jacob', 'Paul', 'Fisher', 'Pancho', 'Dave', 'Teacher', 'Tom', 'Markus', 'Ryan', 'Mark', 'Customer', 'Ron', 'David', 'Father', 'Car Salesman', 'Nick', 'Terry', 'Mechanic', 'Ted', 'Guest', 'Dean', 'Joshua', 'Ronald', 'Customs Officer', 'Peter', 'Mr. Smith', 'Greg','Sam', 'Bank Teller']

females=['Mrs. Smith', "Andrew's Sister", 'Sarah', 'Neighbor', 'Game Show Host', 'Jane', 'Stacy', 'F', 'Susan', 'Sales Associate', 'Jenny', 'Maria', 'Ann', 'Carla', 'W', 'Daughter', 'Julie', 'Server', "Dave's Sister", 'Jan', 'Store Employee', 'Kelly', 'Mother', 'Mary', 'Security', 'Brenda', 'Amanda', 'Ashley', 'Interviewer', 'Ranae', 'Stephanie', 'Wife', 'Nate', 'Hotel Clerk', 'Little Girl', 'Beautician', 'Josh', 'Employee', 'Florist', 'Lisa', 'Mum', 'Alex', 'Travel Agent', 'A', 'Operator', 'W1', 'Woman', 'Girl', 'Amy', 'Older Sister', 'Rachel', 'Vet', 'Emily', 'Diane', 'Jori', 'Telemarketer', 'Sara', 'Nancy', 'Ross', 'The Big Sister', 'R', 'Parent', 'W2', 'Anna Maria']

